Makefile, src/libretro/libretro.c, src/libretro/libretro.mak
On New 3DS, it runs some games surprisingly well.
=> Enable building MAME 2003 on 3DS.

src/ui_text.c
Embellished nag screen as per https://github.com/libretro/mame2003-libretro/issues/9
Screenshot of new screen:
(first ever git change.. please be gentle :))
=> Added instruction for joystick/gamepad users

src/libretro/libretro.c
As spotted by @fr500 in https://github.com/libretro/mame2003-libretro/pull/21 - thanks :)
=> Small correction of last PR

src/libretro/libretro.c
Fixes https://github.com/libretro/mame2003-libretro/issues/27
=> Added sample rate core option

Makefile
Builds on windows now. Fixes https://github.com/libretro/mame2003-libretro/issues/44
should get picked up by the buildbot after this is accepted?
=> Windows support.

src/libretro/osd.c
Sorry @fr500 , missed this crucial fix with all the excitement over the makefile working! Now it will compile.
=> Fix mkdir compile crash in windows.

Makefile
Reverts libretro/mame2003-libretro#52
=> Revert "fix arch,otherwise fails if ARCH is set beforehand"

Makefile, src/libretro/osd.c, src/png.c, src/png.h
Got this working with -O0
Got not time to do more test with -O1, etc
You can add it to the rest of cores
=> (VITA) Initial build with -O0

Makefile, README.md, src/libretro/libretro.c
Added pointer support and refactored mouse code.
Updated readme.
=> Pointer (trackpad/touchscreen) support

README.md
Todos and errors should be Issues now that this is a github repository. First I'm going to clean out entries that have already been created as Issues.
* Input Descriptors (for use in Core Input Remapping): https://github.com/libretro/mame2003-libretro/issues/10
* Artwork support : https://github.com/libretro/mame2003-libretro/issues/50
* High-resolution in vector games (currently limited to 640x480): https://github.com/libretro/mame2003-libretro/issues/30
* Will have errors on 64-bit platforms: https://github.com/libretro/mame2003-libretro/issues/83
Edit: As there were only three left, I created new Issues in the tracker so they could be removed here too.
* Expose all MAME options as Core Options: https://github.com/libretro/mame2003-libretro/issues/102
* errors on platforms without …
=> Update README.md -remove bugs and todos that also have Issues in the tracker

src/cpu/mips/mips3.c
This is meant to address https://github.com/libretro/mame2003-libretro/issues/38
This patch enables Killer Instinct to run with the Windows x86_64 MAME 2003 core. @dankcushions might you be willing to test this on ARM?
At first I tried your approach, backporting a future working version of mips3.c to work with MAME 0.78. Because of all of the memory functions that changed between MAME 0.78 -> MAME 0.79 I ultimately decided this was beyond my skill.
Then as I continued my research, I found old forum reports that the powerpc ports of MAME stopped working with Killer Instinct between MAME .76 and approximately MAME 0.85 although there was never a specific bug report in the MAME release notes.
Sure enough, the MAME 0.75 MIPS3 code works here in x86_64 land! Having enjoyed more than a few …
=> fix bug in c-based MIPS3 emulator

src/drivers/gaelco2.c
Add in the protection handling so this game will be playable
=> Make Snowboard Championship Work

src/drivers/ddragon.c
Apon completing the game in single but mostly in two player mode Double Dragon  can and will crash
this fix from MAME103u2 will prevent that from happening
=> Fix Crash In Double Dragon

src/drivers/neogeo.c
Start with the easy ones and get the libretro2003 neogeo driver on a par with MAME85 with regards to
game support
=> New Working Games

src/drivers/cave.c
Power Instinct Legends from MAME103
=> New Working Game

src/drivers/neogeo.c
Added in the final few games plus a few extra decrypted versions, also tided up the driver
=> Last few NeoGeo games

src/sound/ymf278b.c
This is the commit : 0.79: YMF278B update, improving sound in Asura Blade [R. Belmont]:: but it just seems to raise the channel vol panning by one not sure if we totally need this..??
=> Optional improve sound in Fuukifg3 games

src/drivers/psikyo4.c
IMHO the only game in this driver worth playing is Lode Runner The Dig Fight but it boots with 2 screens
displayed side by side,, by changing the above define it'll boot in single screen mode
=> Optional disable Dual Screen Mode

src/drivers/toaplan1.c
Hook up the recently dumped sound MCU
=> Add Sound To Fire Shark / Same Same Same!

src/drivers/djboy.c
This code comes via iq_132 all i did was rework some of it for the MAME78 codebase
=> Make DJ Boy work

src/drivers/dreamwld.c
Code via iq_132 with some graphical updates by myself for Cute Fighter
=> New Driver which supports 5 games

src/drivers/tetrisp2.c
Added alt version of Rock'n, plus  Rock'n 2, 3, and 4 are now playable
=> Finish off tetrisp2 driver

src/drivers/ssv.c
Dyna Gears new working game
Driftout 94 remove incorrect protection
Monster Slider fix incorrect level logic game now playable
Twin Eagle II add dsp handling and fix graphics game now playable
=> Do more work on SSV

src/drivers/m107.c
Fix sound and improve the bad graphical layer, original code by BP and myself
=> Lets get Fire Barrel playable

src/drivers/aburner.c
Many graphical, sound and input improvements plus two new playable games.
=> Big Sega core update to MAME83

src/drivers/aburner.c
=> Revert Sega Core Update

src/drivers/toaplan2.c
The bootleg plays quite nicely in MAME-2003
=> Lets get FixEight playable

src/machine/irem_cpu.h
This will fix the sound and the sub CPU reset line getting lost in transet slowing the game down to a crawl
=> Forgot that Fire Barrel needs this

src/drivers/m107.c
Fix sound and sub-cpu reset line game will truely be playable now :)
=> For Fire Barrel

src/vidhrdw/sf1_vidhrdw.c
Code is via iq_132 and gives a large speedup and reduction in the overall memory requirements
when loading the graphical Roms for Street Fighter, this works very nicely on the Xbox im sure it'll
be likewise for all the platforms that use this MAME core.
=> Speedup hack for Street Fighter

src/drivers/toaplan2.c
Add in the V-blank changes which were coded at the same time as the video changes happened for the FixEight bootleg i assumed maybe wrongly they were not needed, with a bit of luck this will sort the performance hit in batrider which has been reported on the forums.
Also since i was at it i added support for Knuckle Bash 2 which is just a bootleg of Knuckle Bash but 
unlike that game this one does have full sound.
=> Attempt to fix some reported performance drops

src/driver.h, src/libretro/libretro.c, src/sndhrdw/williams_sndhrdw.c
Reverts libretro/mame2003-libretro#220
=> Revert "Make the Williams speedhack a Core option so it can be disabled for g…"

src/drivers/rockola.c
0.88u7: BUT added sample support to Sasuke' (hit.wav, boss_start.wav, shot.wav, boss_attack.wav).
0.88u7: BUT added speech sample support to Fantasy' (ft_voi-0 - ft_voi-b.wav).
0.88u7: BUT added speech sample support to Vanguard' (vg_voi-0 to vg_voi-f.wav).
0.88u7: MAME32 Improved sample support for Rockola driver HD38880 speech by samples. 
0.81u5: Curt Coder added Vanguard SHOTB sound effect.
0.81u4: Curt Coder hooked up SN76477 sound in Fantasy, Nibbler, Pioneer Balloon, Sasuke and Vanguard
=> Sound improvements

src/drivers/denjinmk.c
Bit of a special is this one converted legionaire driver and video and Seibu Cop Protection
=> Denjin Makai WIP

Makefile.common
sndhrdw/seibu was declared twice, i've put that right now and hopefully all the build errors will be gone
=> This should fix the build

src/drivers/neogeo.c
NeoGeo Roms have been updated many many times over the years as a result the old ones
either get deleted or the links for them die resulting in them being unavailable, with regards
to the new ones i added to this driver i have a correct and working Rom for each of them
via old Xbox Rompacks.
Im currantly making a pack so folks can build new dats and Romsets to support them, one 
game however has eluded me namely the parent and decrypted versions of SNK Vs Capcom
as all my sets just contain the bootleg Rom which im now adding support for to this core
as without it this game would be unplayable due to the correct Roms being lost over time.
=> We need this Bootleg

src/drivers/gaelco.c
Uses encrypted gfx so i've added the decryption code, a small change will be needed in gaelco vidhrdw
as thoop needs the tilemaps to be dirty, finally added screenram for Biomechanical Toy and Manic Square which will net a small graphical improvement in those games
=> New working game Thunder Hoop

src/drivers/deco32.c
code via iq_132 and reworked for the MAME-2003 core.
one of the most heavily protected Data East games gfx, sound and inputs are encrypted, start by adding
in all the needed code into the driver mem maps, inputs, video routines, sound handling, protection and speedup.
=> New working game Night Slashers

src/machine/decocrpt.c
Needed for Night Slashers I made sure to leave the MSB handling intact
=> New Deco 156 decryption

src/drivers/simpl156.c
Due to the changes needed to get Night Slashers playable might as well make more use of them by adding
support for another new working game.
=> Bonus new driver supporting Joe & Mac Return

src/drivers/boogwing.c
Code via iq_132 and reworked for MAME-2003, due to the recent Deco changes i did to get Night Slashers to work meant that all the video and protection this game requires is already present in the source just to need to hook up the Deco102 CPU decryption.
Boogie Wings one of Data East's best games totally unique you wont find another game like it.
=> New driver for Boogie Wings

src/drivers/dietgo.c
via iq_132 and reworked for MAME-2003, adding the Deco 102 CPU decryption for Boogie Wings 
means we can have this game playable too might as well make the code go further
=> New driver for Diet Go Go

src/machine/decoprot.c
Full simulation of the protection for Rohga Armor Force game now playable, also this will fix a possible crash
in Funky Jet plus generally clean up and improve the implementation for the other games.
=> Update for the protection

src/drivers/m92.c
Japanese version of Hook is brighter in color and harder in difficulty.
=> Add Hook Japan Clone

src/driver.c
=> Add Hook (Japan).

src/drivers/pktgaldx.c
Might as well add it here to further take advantage of the recent Data East update, i'll need
to hook in the prot and declare the new games and driver.
=> Forgot about this driver for Pocket Gal DX

src/drivers/bublbobl.c
0.107u3: Trinity and Nicola Salmoria added support for real Bubble Bobble MCU. Added M6801 (1MHz) CPU4 and TAITO JPH1011P MCU rom (a78-01.17).
=> Add proper MCU dump for Bubble Bobble

src/drivers/kaneko16.c
Hopefully this will sort the bad graphics in B Rap Boys and Shogun Warriors if not then i'll just 
demote both games to not working in this core.
=> Fix memory map

src/libretro/libretro.c
I am interested in adding relative path support to address https://github.com/libretro/mame2003-libretro/issues/74
However as I got started I see that libretro.c is pretty disorganized -- probably a reflection of all the work that has gone into update since its creation. At any rate, this is a style change only. No changes to any codepaths since I don't want to mix style changes with functional changes.
Regardless of whether this PR is accepted I'll still try to take a crack at relative paths in the near future.
=> organize libretro.c

src/libretro/libretro.c, src/libretro/osd.c
just used the mame2000 code for the sample update it works why re invent the wheel we know what the  problem is
=> fix bally input

src/libretro/mame2003.c
=> use APPNAME macro to simplify maintaining 2 cores

src/libretro/mame2003.c
=> fix segfault

src/libretro/mame2003.c
see if this was causing the segfault needed fixed anyway thanks to radius for pointing it out. The way the sound has been changed on mame. I dont even think this delta code condition ever come true since we are processing per frame its best to cover all possibilities though.
=> keep buffer within bounds

src/libretro/mame2003.c
slight bug was in the code fixed now.
=> fix mk2 sound

src/libretro/video.c
Fixes https://github.com/libretro/mame2003-libretro/issues/394
=> Use correct aspect ratios

Makefile.common
=> zlib buildfix

src/libretro/mame2003.c, src/libretro/mame2003.h, src/mame.h, src/usrintrf.c, src/vidhrdw/avgdvg_vidhrdw.c, src/vidhrdw/sega_vidhrdw.c, src/vidhrdw/vector.c, src/vidhrdw/vector.h
This is one of the final things I need to do -- I think -- in order to provide baseline compatibility for code between the two forks.
This won't mean that code can just copy and paste back and forth between forks and compile, but it hopefully does mean that code can copy and past back and forth with only a moderate amount of needed refactoring.
=> no-op: update and sync mame.h with plus version

src/artwork.c
artwork isn't active at the moment in this fork, which actually makes it the perfect time to port these fixes from Plus
=> no-op: port artwork coordinate fixes

Makefile.common, src/config.c, src/inptport.c, src/inptport.h, src/usrintrf.c
It's not in use by anything yet though.
=> no-op: add controls.c to build

src/mame2003/mame2003.c
I'm stubbing out the content detection and core option code from plus with this PR but it will be a future commit before I adapt that code and then remove some `#if 0` that is disabling it.
=> no-op: organize mame2003c like plus

src/drivers/avengrgs.c, src/drivers/foodf.c, src/drivers/midtunit.c, src/drivers/midyunit.c, src/drivers/qix.c, src/drivers/rungun.c, src/drivers/taito_f3.c, src/drivers/williams.c
=> hook up nvram bootstraps

src/mame2003/mame2003.c
=> enable dual joystick option

src/inptport.c, src/input.c, src/input.h, src/mame2003/mame2003.c
=> tidy and sync

src/inptport.c, src/mame2003/mame2003.c
=> add 4-way joystick simulation code

src/mame2003/mame2003.c
This basically reads the analog joystick only if its above the deadzone. This means you can now play games like off road racer. There is no functionality change. 
Its just doesn't read the analog(hard coded still) unless a direction is pressed now the code before would always be active because all analogs have a deadzone and mame treats the analog input with a higher priority than digital when mame requests it. 
There is no reason not to improve mame2003 so people using controllers analog controllers can still play games like off road racer.
=> Stop analog locking digital controls out

src/lib/libFLAC/lpc.c, src/lib/libFLAC/stream_decoder.c, src/lib/libFLAC/stream_encoder.c
=> update libflac and ps3 fix

src/mame2003/mame2003.c
=> fix msv2010 build

src/mame2003/mame2003.c
=> fix msvc build

src/mame2003/mame2003.c
=> fix vector resolution

src/cpu/m68000_cyclone/c68000.c, src/cpu/m68000_cyclone/c68000.h, src/cpu/z80_drz80/drz80_z80.c, src/cpu/z80_drz80/drz80_z80.h
=> Some changes on interrupts for Cyclone and DrZ80

src/drivers/avengrgs.c, src/drivers/foodf.c, src/drivers/midtunit.c, src/drivers/qix.c, src/drivers/taito_f3.c
I missing `#include "inptport.h"`
=> Missing includes for bootstraps

src/drivers/kinst.c, src/drivers/midvunit.c, src/drivers/seattle.c, src/machine/midtunit_machine.c, src/machine/midwayic.c, src/machine/midwunit_machine.c, src/sndhrdw/dcs.c
fixes dcs reset, audio issues in midway titles.
=> dcs reset / set active low

src/drivers/cheekyms.c, src/vidhrdw/cheekyms_vidhrdw.c
=> Cheekyms color

src/vidhrdw/system16_vidhrdw.c
=> A small fix for Hang-On Sprites

src/mame.h, src/mame2003/mame2003.c, src/mame2003/video.c
Fix frameskip / add new auto features. Add new cyclone core option.
=> Frameskip and cyclone core options

src/drivers/dkong.c
same as https://github.com/libretro/mame2003-plus-libretro/pull/1267
=> imperfect color flag for dkong romsets

Makefile
=> PS3: update Makefile and remove obsolete variable

.gitlab-ci.yml, src/cpu/arm/arm.c, src/cpu/arm/armdasm.c, src/cpu/v60/am.c, src/cpu/v60/am1.c, src/cpu/v60/am2.c, src/cpu/v60/am3.c, src/cpu/v60/op12.c, src/cpu/v60/op2.c, src/cpu/v60/op3.c, src/cpu/v60/op4.c, src/cpu/v60/op5.c, src/cpu/v60/op6.c, src/cpu/v60/op7a.c, src/cpu/v60/optable.c, src/cpu/v60/v60.c, src/cpu/v60/v60.h, src/cpu/v60/v60d.c
Reverts libretro/mame2003-libretro#484
=> Revert "V60 / Arm"
