libretro/mame2003-libretro

src/libretro/libretro.c, src/libretro/osd.c
Ensure saving of .nvram, mame.cfg, game.cfg, etc, regardless of initial
directory structure. Latter allows useful interim solution until full
core input remapping is implemented.
(+ style nit)
=> Create various mame directories if they don't exist

README, src/libretro/libretro.c, src/libretro/osd.c, src/ui_text.c
Second attempt - see https://github.com/libretro/mame2003-libretro/pull/20
1) Moved internal mame directories to:
- User-generated content: Saves (NVRAM, MEMCARD), Hi-Scores, and Controller Config files are in sub-directories within the Retroarch Savefile Dir.
- Everything else (Cheats, Mame INI, etc) in the Retroarch System/BIOS Dir.
Both sets of directories are within parent /mame2003/ directories, to avoid conflicts with other cores sharing the retroarch directories. e.g. /RetroarchSaveDir/mame2003/nvram/.
Directories will be automatically created if they don't exist.
2) More sensible continue message during Mame warning screen.
3) Enabled samples (now that the directories are generated/polled correctly). Samples are placed in /RetroArchSaveDir/mame2003/sample/gamename.zip
NOTE: …
=> Remapped mame directories to retroarch directories.

src/libretro/libretro.c, src/mame.c, src/mame.h
Allows users to skip the 'this game has graphical issues' etc warnings. Defaults to off (displays warnings)
=> Added skip warnings core option. Defaults to 0.

src/input.h, src/libretro/joystick.c, src/libretro/libretro.c
This adds:
- mouse/trackball support (tested with centipede). only supports 1 mouse - seems like libretro only permits one mouse device as it was giving the same output regardless of port.
- analog joystick support (tested with afterburner). only one analog stick (Left) as that's all mame supports.
...and fixes a samples regression with a previous change (whoops!).
=> Mouse/trackball & analog joystick support (and a samples regression fix)

Makefile
I have ARCH set for pbuilder, which I can workaround, but it seems ARCH defined here for ARM optimizations should be "arch", given it's usage above and throughout the makefile. I also  had success just unsetting ARCH, with : `ARCH :=` in the Makefile.
=> fix arch,otherwise fails if ARCH is set beforehand

Makefile, Makefile.common
This allows setting DEBUG=0 to not build debugging symbols. To match other cores SYMBOLS is not DEBUG and DEBUG is now DEBUGGER to be more clear that it builds the debugger.
=> Make building debugging symbols more like other cores

metadata/highscore.dat
highscore.dat is required by MAME in order to support highscore saving for many games. The [mame2003 core does support this function now](https://github.com/RetroPie/RetroPie-Setup/wiki/lr-mame2003#high-scores) but does not come with the file.
This PR would make the appropriately-versioned highscore.dat easier to locate for mame2003-libretro users and protect against the chance that this old version of the file disappears in the future.
=> add highscore.dat

README.md
There are no mkdir commands in the MAME 2003 Makefile at this point. Seems like this todo is no longer relevant.
=> remove outdated todo

Makefile
This PR has makes two tweaks:
* Add logic to compile MIPS3 engine when ARCH = x86 as passed to make. ARCH = x86 is already specified in all but one x86 buildbot recipe
* If ARCH is not specified, try to detect if those host system is x86 and compile in support
In order for generic Linux x86 to benefit from this, the corresponding buildbot .conf will need an update in libretro-super.
I'm hoping for code review. @dankcushions I'd be glad of any input you have.
I've tested this makefile in Windows where it seems to be working fine, despite some other issues I'm having getting my MAME 2003 build environment set up under MYSYS2.  Any hints about that are also welcome.
=> Update Makefile to compile in MIPS3 engine for x86

src/libretro/osd.c
OSD does not take into account fractional part of sample_rate / fps calculation.
This can lead to accumulating "missed" samples" causing DCS internal buffer overflow and potentially other audio issues in other MAME drivers.
This PR only touches OSD audio code so this should also improve accuracy of audio emulation of the whole mame2003-libretro core.
I have tested around 10 different MAME games without any other side-effect or regression.
=> Temptative fix for DCS sound games issue.

README.md
Adds a link to the new RetroArch documentation. @dankcushions and others might notice that there are some pretty familiar passages: the RetroPie docs were invaluable sources. I've tried to make sure to give some credit here.
=>  Add link to RetroArch documentation/give credit

Makefile
This issue come from windows. It can't handle too much object in 1
command.
=> It fix compilation issue with large number of object

metadata/catver.ini, src/drivers/snowbros.c
This PR is based on a current fork to clear up the conflict in my earlier PR.
This PR corrects some "playability" information based on my testing with the original MAME 0.78 executable. I'm also cross referencing [the RetroPie crowdsource testing of MAME 2003 romsets](https://docs.google.com/spreadsheets/d/1LP1MELCvcxu7TfiowF_0ZuvRVEMqlfQyTVetnOJvuJc/edit?usp=sharing).
I'm contemplating a process to help check and correct this information for all of the games, but for now here is at least the first section, hand-corrected.
=> fixed- update game playability information (romsets starting with #s)

src/vidhrdw/midtunit_vidhrdw.c
This fix from MAME114 will stop the game randomly crashing at the end of a level
=> Fix random crash in Rampage World Tour

src/ui_text.c
Bringing this common error message up to date for the libretro-mame2003 era.
=> updated and more helpful cocktail error message

src/driver.c
Extra version of Shadow Dancer no longer supported
=> Sega Core Revert

src/drivers/dkong.c
0.86u3: Donkey Kong sample improvements [Peter Rittwage, Derrick Renaud]. Added samples (run01, run02, run03, jump and dkstomp.wav).
0.86u3: Peter Rittwage and Derrick Renaud replaced the old climb and walk sample with three different samples. Replaced climb- and walk.wav with climb0, climb1 and climb2.wav and walk0, walk1 and walk2.wav.
Code via BritneysPAIRS
=> Improve sample sounds in Donkey Kong and Donkey Kong JR

src/vidhrdw/midvunit_vidhrdw.c
0.94u5: Aaron Giles turned off debugging code in the hotspots, giving a huge speed improvement to the V-unit games.
=> Big performance boost for Midway V-Unit

src/sndhrdw/rockola_sndhrdw.c
0.88u7: BUT added sample support to Sasuke' (hit.wav, boss_start.wav, shot.wav, boss_attack.wav).
0.88u7: BUT added speech sample support to Fantasy' (ft_voi-0 - ft_voi-b.wav).
0.88u7: BUT added speech sample support to Vanguard' (vg_voi-0 to vg_voi-f.wav).
0.88u7: MAME32 Improved sample support for Rockola driver HD38880 speech by samples. 
0.81u5: Curt Coder added Vanguard SHOTB sound effect.
0.81u4: Curt Coder hooked up SN76477 sound in Fantasy, Nibbler, Pioneer Balloon, Sasuke and Vanguard
=> Sound improvements cont

src/drivers/simpl156.c
Added support for the rest of the games barring Party Time Gonta The Diver 2 as it's not working, 
Osman, Charlie Ninja, Chain Reaction and clones will require a small change in the ARM CPU to fix 
some graphical problems, original code via iq_132 and reworked for MAME-2003
=> Finish off the simpl156 driver

src/drivers/neogeo.c
Some were plain ole malloc while others where UINT8 malloc, lets go with UINT 8 for all of them
=> Sort the malloc mismatches

src/libretro/libretro.c
per discussion with @caver01 here: https://github.com/libretro/mame2003-libretro/issues/30#issuecomment-371059228
Part of an ongoing process to get mame2003 vector as good as mame 0.78.
I'm not sure that `beam_width` is doing anything, at least not with Tempest. I notice that later versions of MAME use a `float` for that value instead of `int`. Maybe this works as-is with other games than Tempest though.
=> add remaining vector options

src/drivers/stv.c, src/drivers/system16.c
These are more corrections stemming from the work of @grant2258 in the RetroPie forums. Helping get these old MAME cores tight as a drum!
=> update a few more GAME_NOT_WORKING flags

Makefile
per suggestion by @retro-wertz to only execute bin2c manually when needed, at least until there is a more sophisticated approach in the makefile
=> default BUILD_BIN2C to disabled

src/vidhrdw/namcos1_vidhrdw.c
this will not optimize the bad code that breaks namcos1 on a few builds not sure how many no need to unoptimize the whole driver
=> dont optimize code that breaks on most builds

src/sound/es5506.c
=> fix es5506 (SSV games sound driftout95 twin eagel ect)

src/libretro/mame2003.c
== DETAILS
When the APPNAME macro was added, the libretro code was included
in the change and doing so broke netplay in RetroArch.
RetroArch stores core information in *.info files, and the `corename`
field of the info file is expected to match what the core self-reports.
The result of the APPNAME macro work is that it changed the self-reporting
core name as "mame2003".
This commit changes the core self-reported name (and JUST that name) back
to the expected value.
== TESTING
Tested locally and confirmed that the content matching in netplay is now
successful.
@twinaphex 
Please note that by contributing code or other intellectual to this project you are allowing the project to make unlimited use of your contribution. As with the …
=> change core name as reported to the libretro API to match the RA .info file

src/libretro/mame2003.c, src/libretro/video.c, src/mame.c, src/mame.h, src/vidhrdw/vector.c
Finally sat down and made a clean fix for #332.
The problems were: incorrect beam width setting parsing leading to an infinite loop on antialias enabled; plain wrong resolution multiplier setting handling leading to a clipped screen; incorrect memory buffer handling leading to crashes. All fixed.
As an extra, I've set the default color depth for non-palette modes to 32bpp as used by video.c internally. A no-brainer, really - the core otherwise wastes an exorbitant amount of time doing the conversion every frame. This yields noticeable FPS increase on higher output resolutions.
Will post more details on the issue page.
=> Fix vector graphics rendering settings

src/libretro/mame2003.c
This clarifies that the core itself must be restarted to enable vector antialiasing to avoid confusion with resetting the content.
This also syncs up the descriptions and default values for the vector options between mame2003 and mame2003-plus where they had diverged a little bit. I'll be putting in a PR in for this purpose in the other repo too.
=> indicate core restart for antialias option, sync default vector options

src/libretro/mame2003.c, src/libretro/video.c, src/mame.c
This PR should fix all games formely unplayable due to screen mirroring issues, as reported in #386. Such games include Gunbuster, Solar Quest, Atari Starship, Battle Shark. It also falls back to doing flipping/rotation natively if libretro frontend doesn't support hardware rotation.
There are possible performance issues: I didn't add any frame copying bypasses, and the bitmap transpose is done naively, where it probably should be done by a cache-oblivious matrix transpose algo. This is done to keep code complexity down, and may be remedied if there's need for it. Future work may also include requesting a hardware framebuffer from libretro, to keep buffer copying down.
=> Native screen rotation/flipping support

src/libretro/mame2003.c, src/libretro/video.c, src/mame.c
Finally made a proper fix for #386 & #341, after the botched one at #389. While suboptimal (see below), it should actually handle all rotations correctly, both with or without libretro rotate support. TATE mode now works, too. I've also done some refactoring, moving all orientation-related parts to video.c. All in all, the code should now be more readable and maintainable. Sorry for the long wait, and thanks @grant2258 for testing the previous fix and pointing me in the right direction!
Oh, and please do contact me if you want to merge this in mame2003-plus, I prefer to make the necessary changes myself.
What else can be done:
- Using libretro's rotations for image transpose, when an exact rotation is unavailable. I'm just not smart enough to do all this bit fiddling, so I got fed up and …
=> Native video rotation fixes, cleanups, refactoring

src/libretro/mame2003.c
This was requested months ago by a user that disappeared from the issue, but I never got the bypass working anyway. Today I don't even thing this was a good idea for the core.
=> remove non-functional romset verify bypass

Makefile.common, src/libretro/mame2003.c, src/libretro/mame2003.h, src/mame.h, src/mame2003/log.h
A lot of the fun new functionality in mame2003-plus involves core options that are tracked by the options struct in mame.h.
This PR doesn't change any functionality but it resolves the merge conflicts between the two versions of the file so that we can selectively add some of the fun stuff to this version of the core.
=> no-op - stub out core option variables and log interface

src/hiscore.c, src/hiscore.h, src/libretro/mame2003.c, src/mame.h
And if there isn't one present, one is generated. This is the behavior in 2003-plus
=> always use external hiscore.dat if present

src/drivers/xevious.c
=> fix xevious samples

src/sndhrdw/astrocde_sndhrdw.c
This line cause errors in compiler checking. https://build.opensuse.org/package/live_build_log/Emulators/libretro-mame2003/openSUSE_Leap_15.1/x86_64
I followed this https://www.wikihow.com/Compare-Two-Strings-in-C-Programming
---
=> Correct way to compare string

src/mame2003/mame2003.c
Similar to https://github.com/libretro/mame2003-plus-libretro/commit/e1e61ec21ba1311f37adf24134f3f2b392d33bbe, also reported at https://github.com/libretro/RetroArch/issues/8685.
=> fix cheat input dip switch option

src/drivers/ashnojoe.c
0.128u2: Phil Bennett fixed MSM5205 ADPCM and sound communications in Ashita no Joe/Success Joe.
0.122u1: Corrado Tomaselli verified some CPU clocks of original boards using a frequency counter, changed Success Joe YM2203 clock from 3MHz to 4MHz.
=> Fix speech and sfx sample playback for Ashita no Joe [arcadez ported]

src/drivers/sharrier.c
Fix up the background and road graphical layers game now playable
MAME WIP
15th March 2004: Charles MacDonald made various Hang-On fixes: Fixed sprite, tile and shared RAM (2nd 68000) size in hangon - RAM test works, fixed visibility of 2nd 68000 ROM to 1st 68000, passes ROM test, fixed access to road RAM and shared RAM by both CPUs - road layer works again and added proper emulation of the I/O hardware in hangon: Cleaned up input management, now entering test mode does not crash MAME, there are no specific control hacks for the name entry screen, and the ROM patches are no longer needed.
Please note that by contributing code or other intellectual to this project you are allowing the project to make unlimited use of your …
=> Fix for Sega's Hang-On

src/drivers/contra.c
furrtek Added Konami 007452 multiplier/divider fixes rolling mines trajectories in contra
Rather than add a whole new device im just hooking it directly into the Contra driver for this core
Combat School Flak Attack and WACLeMans also use this but for now im focusing on Contra as
the game improvements are known
Whereas with the others the benefits over the original simulations are not as yet known if indeed there are any.
**This license can be viewed at …
=> Contra protection improvements

Makefile
RS90 Support.
Loaded and ran centipede as test.
More information about the platform here: https://github.com/libretro/RetroArch/pull/12592
=> RS90 Support

src/drivers/dkong.c, src/vidhrdw/dkong_vidhrdw.c
This modification brings the palette used in dkong exactly in line with that of FBNeo which is considered to be correct. The main change in appearance is that the  platforms along which the barrels roll and Mario climbs now have a deep pink colour as oppose to red.
=> adjust dkong palette to match observed rgb values from fbneo

src/drivers/snk.c
@mahoneyt944 
Hi, thanks for getting back to me and offering to review.  Here is the patch for the issue submitted as a pull request as directed.  I have also pasted what I posted in the issue here below.  Let me know if there are questions.
-----
I investigated this, and it looks like this issue is caused by a bug fix which intentionally feeds a invalid code to avoid a bug with Guerilla War.
I also came up with a patch (now this pull request) that automatically rotates to the next code (which is a good code) that the character was rotating to in the next frame.  So, the bug fix for Guerilla war still works, but the user never perceives the character did not rotate when the 12 way joystick is rotated.
Let me know if there are issues with the patch, method of fixing this bug, etc.  I'm …
=> Workaround invalid rotate code

src/inptport.c, src/inptport.h, src/ui_text.c, src/ui_text.h, src/usrintrf.c
Hi @mahoneyt944 ,
This is the same patch that I did for mame2003-plus, adding the "X-Way Joystick" option to the Analog Controls menu only for IPT_DIAL and IPT_DIAL_V devices.  Enabling the X-Way Joystick option eliminates one rotary step of a X-Way rotary joystick from sometimes rotating the character 2 rotary steps.
This basically combines the codes used in these two PRs in mame2003-plus:
https://github.com/libretro/mame2003-plus-libretro/pull/1652
https://github.com/libretro/mame2003-plus-libretro/pull/1740
It has been about two weeks since those PRs settled, and I didn't see anything mentioned in the issues list, so I assume no bugs have been discovered.
Also, question for you.  Is there a good place to put recommended key/joy step, sensitivity, and x-way joystick settings for each of …
=> Avoid multiple detect from single12way rotate

CHANGELOG.md, src/drivers/seta.c
Hi @mahoneyt944 ,
This PR does the same thing as this mame2003-plus PR that I submitted a day or two ago:  https://github.com/libretro/mame2003-plus-libretro/pull/1765
Relisting those changes here:
- Adjust the default (initial) value of the Dial Analog Port for the game DownTown to put it in the middle of the range of the rotary step. This keeps precession from causing the character to lose or gain an extra step for about 30 twists continuously in one direction (for both directions).
- - by modifying the JOY_ROTATION macro (which generates the PORT_ANALOGX macro for Caliber 50 and DownTown keeping the default value of Caliber 50 the same, and changing the default value of DownTown
- Changed recommended key/joy step for DownTown to make it work the best with this change
Thank you wanting …
=> Put DownTown rotary initial value to middle of range in rotary step
